### ISSUE TITLE
파일 구조들의 정리에 관하여

### ISSUE THREAD

**Issue by Youshin** [pendermask/gwangpal#1]
. 폴더
|--- Img folder
|          └ 이미지 파일들
|--- Style folder
|          └ .css 파일들
|--- js folder
|          └ .js 파일들
|--- 그외 html 파일들

지금껄 굳이 수정하라는건아니구, 위의 구조가 제일 Standard 한 구조에요. 추가적으로 html 파일명만 보고 이게 무슨 페이지에 관련된것이다라는거라도 알수있으면 더욱 좋겠죠.

**Comment by youshink** [comment]
CSS 정리하실때부턴 저렇게 해보셔요.
